packages:
  - 'packages/*'
  - 'examples/*'
  - 'guide'
  - 'playground'

minimumReleaseAge: 10080

allowBuilds:
  deasync: true
  esbuild: true
  msw: false
  sharp: true
  workerd: true

linkWorkspacePackages: true
