/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FileUploadRouteImport } from './routes/file-upload'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignupAsyncSchemaRouteImport } from './routes/signup-async-schema'
import { Route as TodosRouteImport } from './routes/todos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileUploadRoute = FileUploadRouteImport.update({
  id: '/file-upload',
  path: '/file-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAsyncSchemaRoute = SignupAsyncSchemaRouteImport.update({
  id: '/signup-async-schema',
  path: '/signup-async-schema',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file-upload': typeof FileUploadRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/signup-async-schema': typeof SignupAsyncSchemaRoute
  '/todos': typeof TodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file-upload': typeof FileUploadRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/signup-async-schema': typeof SignupAsyncSchemaRoute
  '/todos': typeof TodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/file-upload': typeof FileUploadRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/signup-async-schema': typeof SignupAsyncSchemaRoute
  '/todos': typeof TodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/file-upload'
    | '/login'
    | '/signup'
    | '/signup-async-schema'
    | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/file-upload'
    | '/login'
    | '/signup'
    | '/signup-async-schema'
    | '/todos'
  id:
    | '__root__'
    | '/'
    | '/file-upload'
    | '/login'
    | '/signup'
    | '/signup-async-schema'
    | '/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileUploadRoute: typeof FileUploadRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SignupAsyncSchemaRoute: typeof SignupAsyncSchemaRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-upload': {
      id: '/file-upload'
      path: '/file-upload'
      fullPath: '/file-upload'
      preLoaderRoute: typeof FileUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-async-schema': {
      id: '/signup-async-schema'
      path: '/signup-async-schema'
      fullPath: '/signup-async-schema'
      preLoaderRoute: typeof SignupAsyncSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileUploadRoute: FileUploadRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SignupAsyncSchemaRoute: SignupAsyncSchemaRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
