// Generated by Wrangler on Fri Apr 05 2024 00:43:41 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	CACHE: KVNamespace;
	CF_PAGES_BRANCH: "main";
	LANGUAGE: "en";
	GITHUB_ACCESS_TOKEN: string;
}
