name: Pre-release
on:
  push:
    branches: [main]

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Publish to pkg.pr.new
        run: pnpx pkg-pr-new publish --compact './packages/*'
