name: Preview
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: |
          npm i -g corepack@latest
          corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Publish to pkg.pr.new
        run: pnpx pkg-pr-new publish --compact './packages/*' --template './examples/*'

  validate:
    name: Validate Preview
    needs: [release]
    uses: edmundhung/conform/.github/workflows/validate.yml@main
    with:
      preview: ${{ github.event.pull_request.number || github.sha }}
