name: Release
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  pull-requests: write
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup pnpm and Node
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          runtime: node@24
      - name: Build packages
        run: pnpm build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@198f833dd7d863100ea6e28967bc9a9fdefadb0a # v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-with-git-cli: false
          pr-title: 'release: bump packages version'
          commit-message: 'release: bump packages version'
          version-script: pnpm run version
          publish-script: pnpm exec changeset publish
          create-github-releases: false
          push-git-tags: true
